### PR TITLE
Allow parsing from binary streams

### PR DESCRIPTION
**Pull request by carantunes**
Closes https://github.com/chrismattmann/tika-python/pull/240/files

### CODE REVIEW

**Comment by carantunes** [comment]
Hello,
I've just checked this is still only on master. Do you have an estimate to when will it be released on a tag?

**Comment by chrismattmann** [comment]
hi @carantunes I usually time the releases to go along with Tika Java and its core release, but could probably get this out  sooner. Let me try.

**Comment by carantunes** [comment]
Thank you, it would be super usefull! In that case you could release a 1.23.1

**Comment by carantunes** [comment]
Ping! Any news on this? @chrismattmann

**Comment by chrismattmann** [comment]
sorry @carantunes I'll try and find time this weekend! Been a busy month! I just released a new book, [Machine Learning with TensorFlow, 2nd edition](https://www.manning.com/books/machine-learning-with-tensorflow-second-edition?a_aid=5700fc87&a_bid=1e05f0bb) and have been busy promoting that!

**Comment by chrismattmann** [comment]
@carantunes i pushed 1.23.1 to PyPi, give it a shot!

**Comment by carantunes** [comment]
Thank you so much!

Congratulations and best of luck with your new book. I'll check it for sure! :)

**Comment by chrismattmann** [comment]
thanks @carantunes

**Pull request merged**
