### PR TITLE
fix for shell dependency

### PR DESCRIPTION
**Pull request by ahmadia**
* write log in tika-server.log

This set of revisions were originally in
a80f419bd7ec69c8dbac76d6329989527eb8e87f and have been rebased.

### CODE REVIEW

**Comment by ahmadia** [comment]
@dongnizh and @chrismattmann - this is ready for review.

**Comment by dongnizh** [comment]
Thanks @ahmadia. That is great!!!

**Comment by ahmadia** [comment]
@dongnizh / @chrismattmann  - when you get a chance, you'll want to reset your repository to point to the rebased master branch.  It is really important *not* to `pull` or `merge`, you need to either delete your old branches or rebase them against the new version.

Some details here: http://superuser.com/questions/273172/how-to-reset-master-to-origin-master

As well as here: http://stackoverflow.com/questions/4084868/how-do-i-recover-resynchronise-after-someone-pushes-a-rebase-or-a-reset-to-a-pub

**Comment by dongnizh** [comment]
@ahmadia Thanks for your suggestion. Will do it later.

**Comment by chrismattmann** [comment]
great work, merging this! @ahmadia can you please give me a set of commands for this rebase thing I have no clue how to do it.

**Comment by chrismattmann** [comment]
also @ahmadia can you add yourself to the Contributors list in the README.md file?

**Comment by ahmadia** [comment]
@chrismattmann - if you don't have any work that hasn't been merged yet:

```
git fetch
git checkout master
git reset --hard origin/master
```

If you have unmerged work, save it in a branch, and I'll show you in person on Thursday :)

**Comment by chrismattmann** [comment]
woot, ok I ran your commands, seemed to work!

```
[chipotle:~/git/tika-python] mattmann% git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[chipotle:~/git/tika-python] mattmann% git fetch
remote: Counting objects: 142, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 142 (delta 2), reused 0 (delta 0), pack-reused 127
Receiving objects: 100% (142/142), 27.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (28/28), done.
From https://github.com/chrismattmann/tika-python
 + f14aedb...f670f9c master     -> origin/master  (forced update)
 * [new branch]      backup-master -> origin/backup-master
[chipotle:~/git/tika-python] mattmann% git checkout master
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 113 and 111 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
[chipotle:~/git/tika-python] mattmann% git reset --hard origin/master
HEAD is now at f670f9c Merge pull request #41 from chrismattmann/dongnizh/shell-dependency-fix
[chipotle:~/git/tika-python] mattmann% 
```

Thanks @ahmadia !

**Comment by ahmadia** [comment]
Yup, that's exactly what I expected to see.

**Pull request merged**
