### PR TITLE
Tika 1.24.1 - gzip (de)compression

### PR DESCRIPTION
**Pull request by carantunes**
Closes https://github.com/chrismattmann/tika-python/issues/305

Bump Tika to 1.24.1
Add tests for benchmarking gzip compression

### CODE REVIEW

**Comment by carantunes** [comment]
In another topic please consider removing support for python 2.7 as it reached EOL on January 1st, 2020 and it considerably slows downs development.

**Comment by carantunes** [comment]
Is travis not running anymore?

**Comment by chrismattmann** [comment]
thanks @carantunes I'll review this week. Just got back from vacation. How should I remove python2.7? I'm not *explicitly supporting it" per-se, I am using python3.7 as my core dev environment. Do you mean remove it from Travis?

**Comment by carantunes** [comment]
Hi, I was on vacation as well. 
Yes, I assumed from Travis python 2.7 support was mandatory. 
In that case if you wish, after this one is merged, I can contribute removing explicit python 2.7 support code segments and from Travis as well.

You can also add the explicit minimum required python version with `python_requires`:

```
setup(
...
   python_requires='>3.6',
...
)
```

or just hint it with a classifier:
```
setup(
...
    classifiers=[
        ...
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        ...
    ],
...
)
```

**Comment by chrismattmann** [comment]
sorry it took me so long @carantunes! merged. Will release as part of the next release.

**Pull request merged**
