### PR TITLE
Py3 fix

### PR DESCRIPTION
**Pull request by yashtanna93**
Fixed the python 3 errors

### CODE REVIEW

**Comment by yashtanna93** [comment]
@chrismattmann  please check this commit

**Comment by Pehat** [comment]
[This fix](https://github.com/yashtanna93/tika-python/blob/py3-fix/tika/tika.py#L64) seems to be incorrect. When you compare types via `is` statement, the right-hand side must be a type, not a string representing a codec; see usage in [this](https://github.com/yashtanna93/tika-python/blob/py3-fix/tika/tika.py#L288) line and fix me if I'm wrong.

**Comment by Pehat** [comment]
Codec name is not a type. It's a binary string in Python 2 and a unicode string in Python 3.
 in [this](https://github.com/yashtanna93/tika-python/blob/py3-fix/tika/tika.py#L288) line you check whether the `data` has a type that allows you to `.decode` it into the binary string. Comparison with a `'utf_8'` string constant is meaningless here:

```
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 'asdf' is 'utf_8'
False
>>> u'asdf' is 'utf_8'
False
```

**Comment by yashtanna93** [comment]
I will look into this

**Comment by Pehat** [comment]
Look into [this](https://docs.python.org/2/howto/unicode.html), it helps a lot not to mix bytes, codecs, and abstract glyphs.

**Comment by chrismattmann** [comment]
thanks @yashtanna93 !

**Comment by Pehat** [comment]
@chrismattmann , have you read the conversation in this thread? The last commit [is breaking type-checking](https://github.com/chrismattmann/tika-python/pull/86#issuecomment-202776291), so that @yashtanna93 closed it in order to fix it. Be careful. I'll send some tests and fixes today.

**Pull request merged**
