### PR TITLE
Add killServer() function

### LINKED ISSUE #235: Tika server never ends, consuming RAM after usage
After processing all the PDFs I needed, I noticed that the Tika server was still up and running in the background, eating a lot of RAM (usually between 1~1.8gb after having processed ~4000 PDFs).

```
ps -o pid,rss,command 4017   
  PID   RSS COMMAND
 4017 1252128 java -cp /tmp/tika-server.jar org.apache.tika.server.TikaServerCli --port 9998 --host localhost
```

Is there a way to end the server after doing everything needed, through the library itself? If not, a `tika.stopVM()` would be something interesting to have.

### PR DESCRIPTION
**Pull request by igormp**
Allows us to kill the tika server and clean up some ram. Fixes #235

I still need to test if everything is working fine, so I'll leave this as a draft for now.

Another thing that I was thinking about was to automatically call this function when the program ends. I believe this could be achieved through [atexit](https://docs.python.org/3/library/atexit.html) ([source](https://stackoverflow.com/a/3850271/4542015)).

### CODE REVIEW

**Comment by chrismattmann** [comment]
looking good as a start. Probably good to add a unit test to it thanks @igormp

**Comment by igormp** [comment]
Sure thing. I'm kinda busy this week, but will try to work on it as soon as I can. 

If someone wants to get some work done on it before I do, feel free to do so.

**Comment by chrismattmann** [comment]
hey @igormp let me know if you have time to make more progress on this thanks!

**Comment by igormp** [comment]
Hi, sorry for the long delay :sweat_smile: 

Since we have `shell=True`, the actual Tika process is spawned as a child of the shell, which seems to die soon after the actual tika process starts, leaving the tika process without a parent and no information on its actual PID so we can kill it later on.

I'll try to find a way around that (maybe by looking for the shell's children before leaving the `startServer` function?) and report back as soon as I can.

**Comment by igormp** [comment]
Ok, finally got it working, now it's time to add some tests.

**Comment by igormp** [comment]
Dealt with another weird thing.

For context, I'm adding the following test in the `test_tika.py` file:

```python
def test_server_killed(self):
    """parse some file then kills server"""
    file = os.path.join(os.path.dirname(__file__), 'files', 'rwservlet.pdf')
    with open(file, 'rb') as file_obj:
        tika.parser.from_file(file_obj)
    self.assertIsNone(tika.tika.killServer())
```

Simple enough, right? If I leave it be as it is, it works perfectly fine and kills the server without any problems.

However, if I let it run as the first test by naming it `test_kill_server`, then for some reason the remaining tests start to fail, no matter which test is the next one. 
I guess that's because the server doesn't end immediately, so the next test still thinks the server is up, and then it exits during its execution. This is probably the reason, due to the fact that adding a 1 second sleep after killing the server solves our problems.

For now, I'll leave the 1 second sleep inside the function since it works, we can discuss a better solution if needed.

**Comment by igormp** [comment]
Everything seems fine. A couple points that we need to keep in mind for future discussion:

- If the tika server was already running before our code execution, we won't be able to grab it's PID (since we do it when we start it ourselves), thus won't be able to kill it.
- Should we try to automatically kill the server? On one hand, we could kill it after every parse, which would be simple enough, but would add tons of overhead in case someone was doing multiples parses one after another.

**Comment by chrismattmann** [comment]
I would say @igormp that we don't kill after every parse. If it was running before our execution, I think we simply log that message and do a no op. Fair?

**Comment by igormp** [comment]
Sure thing. That's how I have it set up at the moment.

**Comment by chrismattmann** [comment]
LGTM and time to merge thanks @igormp !

**Comment by chrismattmann** [comment]
hey @igormp I'm getting periodic failures with this PR merged in 1.23.1, see:

```
test_ascii (tika.tests.tests_unpack.CreateTest) ... ok
test_utf8 (tika.tests.tests_unpack.CreateTest) ... ok

======================================================================
ERROR: test_kill_server (tika.tests.test_tika.CreateTest)
parse some file then kills server
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mattmann/git/tika-python/tika/tests/test_tika.py", line 63, in test_kill_server
    self.assertIsNone(tika.tika.killServer())
  File "/Users/mattmann/git/tika-python/tika/tika.py", line 694, in killServer
    os.killpg(os.getpgid(TikaServerProcess.pid), signal.SIGTERM)
OSError: [Errno 3] No such process

----------------------------------------------------------------------
Ran 17 tests in 123.960s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=17 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=17 errors=1 failures=0>
pomodoro:tika-python mattmann$ 

```

Any ideas for a fix?

**Comment by chrismattmann** [comment]
looks like maybe adding your wait idea would help and we also have to catch that occasional OSError and print something sensible about it. @igormp

**Comment by igormp** [comment]
Hey, Chris! Sorry for the long delay once again :sweat_smile: 

I've made another PR that should solve this problem.

**Comment by chrismattmann** [comment]
thanks @igormp

**Pull request merged**
