### PR TITLE
unpack: use with blocks when handling files

### PR DESCRIPTION
**Pull request by carantunes**
I'm trying to reduce the memory usage in unpack. 

Changes:
-  all files usages now use a `with`  block, in order to make sure files are closed and possibly avoid memory leaks.

### CODE REVIEW

**Comment by chrismattmann** [comment]
thanks  @carantunes !

**Comment by carantunes** [comment]
Could you a release a patch as soon as possible? Thank you!

**Comment by chrismattmann** [comment]
yes, and you've submitted so many quality patches, I am going to add you to the contributors file, @carantunes you are at CERN, right?

**Comment by carantunes** [comment]
Yes, I am. Thank you so much :)

**Pull request merged**
