### PR TITLE
 deleted useless comments and added port checking in parser/detector/config

### PR DESCRIPTION
**Pull request by dongnizh**
Hi, @chrismattmann added it. Try it.

### CODE REVIEW

**Comment by chrismattmann** [comment]
@dongnizh we can add requests as a dependency in setup.py - can you update this PR and do that? then no need to have a manual step.

**Comment by dongnizh** [comment]
@chrismattmann  This is for checking port is open or not. If that port is not open, we need to start it. 
BTW, I will delete the prerequisite in README.md. But I do not know how to add it in setup.py.

**Comment by dongnizh** [comment]
I mean testing for JAR running.

**Comment by chrismattmann** [comment]
Great work. I'll add it in setup.py it's easy! :+1:

**Pull request merged**
