### PR TITLE
fix for shell dependency

### PR DESCRIPTION
**Pull request by dongnizh**
@chrismattmann Try this one. I changed it to subprocess and tested this working fine on Ubuntu. Tested on virtual windows and worked fine. 
96516127-66ce-46a3-b00e-bb308e5d9aca
3cf2270e-b060-4a52-ae3c-e206482040a9

### CODE REVIEW

**Comment by ahmadia** [comment]
@dongnizh 

I've cleaned up the git history by removing the .jar files from the history of the repository.  If it is not hard to do, can you rebase your changes onto the new "master" branch?  If not, I can set up a new PR/branch for you to work with.

**Comment by dongnizh** [comment]
@ahmadia  Sure. Close this first and create new pr on your new master branch. Thanks for letting me know this.

**Comment by ahmadia** [comment]
Yeah, I'll do the rebase.

**Comment by ahmadia** [comment]
See #41

**Pull request closed without merging**
