### PR TITLE
Add binary stream functionality to parser.py from_file

### PR DESCRIPTION
**Pull request by prough21**
I have a case where I need to be able to submit binary streams to the parser interface from_file function rather than file paths.

### CODE REVIEW

**Comment by chrismattmann** [comment]
can you provide a unit test with this? @prough21

**Comment by chrismattmann** [comment]
thanks for adding the test @prough21 can you resolve the conflicts with tika/tika.py?

**Comment by carantunes** [comment]
I would be great to have this merged! I also need this feature

**Comment by chrismattmann** [comment]
happy to merge it, but it currently has conflicts @carantunes can you or @prough21 please resolve the conflicts and/or submit a new PR that has this rebased? Thanks!

**Comment by carantunes** [comment]
@chrismattmann @prough21 I provided a new PR: https://github.com/chrismattmann/tika-python/pull/269 with the rebase.

**Comment by chrismattmann** [comment]
thanks I'll check it @carantunes

**Pull request closed without merging**
