### PR TITLE
Added comment to encode response in UTF-8

### PR DESCRIPTION
**Pull request by karanjeets**
This helps when you want to write response, with special characters, into a file.

### CODE REVIEW

**Comment by chrismattmann** [comment]
Hey @karanjeets why not make this an optional parameter in the function or a module variable that if set causes the encoding to kick in?

**Comment by karanjeets** [comment]
@chrismattmann Added --exclude parameter in the script. Does this work ?

**Comment by chrismattmann** [comment]
awesome thanks @karanjeets can you run the tests by typing:

`python setup.py test`

and make sure all is good?

**Comment by karanjeets** [comment]
@chrismattmann Done. Everything looks good.

```

----------------------------------------------------------------------
Ran 24 tests in 58.377s

OK
ok

----------------------------------------------------------------------
Ran 5 tests in 126.395s

OK
````

**Pull request merged**
